name: deploy-hackernews-app-heroku

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Run production migration
        run: npm run migrate:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heorku_api_key: ${{ secrets.KEROKU_API_KEY }}
          heorku_app_name: ${{ secrets.KEROKU_APP_NAME }}
          heorku_email: ${{ secrets.KEROKU_EMAIL }}
